# Copy/paste example from https://github.com/marketplace/actions/electron-builder-action
name: Build/release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install packages
        run: npm install

      - name: Run predefined build process
        run: npm run make

      - name: Create release assets
        uses: papeloto/action-zip@v1
        with:
          # TODO Mac/Linux paths?
          files: dist/win-unpacked
          dest: dist/WebClient.zip

      - name: Publish release assets
        uses: softprops/action-gh-release@v1
      #     # If the commit is tagged with a version (e.g. "v1.0.0"),
      #     # release the app after building
      #     release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          files: dist\WebClient.zip
        env:
          github_token: ${{ secrets.github_token }}
      # - name: Build/release Electron app
      #   uses: samuelmeuli/action-electron-builder@v1
      #   with:
      #     # GitHub token, automatically provided to the action
      #     # (No need to define this secret in the repo settings)
      #     github_token: ${{ secrets.github_token }}

      #     # If the commit is tagged with a version (e.g. "v1.0.0"),
      #     # release the app after building
      #     release: ${{ startsWith(github.ref, 'refs/tags/v') }}
      #     args: --config build.json