name: Test

on:
  push:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-18.04, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install development dependencies
        run: npm install --also=dev

      - name: Run automated tests
        run: npm test